[package]
name = "proxy-browser"
version = "1.0.0"
authors = ["planet0104 <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
scraper = "*"
hex = "0.3.2"
rocket = "0.4.0"
uriparse = "0.6.0"
rocket_contrib = "*"

[profile.release]
lto = true
opt-level = "s"